# Generated by Django 3.1.6 on 2021-02-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
                ('slug', models.SlugField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OcsPsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField()),
                ('procedimentos', models.ManyToManyField(to='fusex.Procedimento')),
            ],
        ),
    ]
