# Generated by Django 3.1.6 on 2021-02-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fusex', '0002_ocspsa_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusex.beneficiario')),
                ('procedimento', models.ManyToManyField(to='fusex.Procedimento')),
            ],
        ),
    ]
