# Generated by Django 3.1.6 on 2021-02-09 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fusex', '0003_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
