# Generated by Django 3.1.2 on 2020-11-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
            },
        ),
        migrations.CreateModel(
            name='PostGraduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Posto/Graduação',
                'verbose_name_plural': 'Postos e Graduações',
            },
        ),
        migrations.CreateModel(
            name='RegisterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Identificação',
                'verbose_name_plural': 'Tipos de Identificação',
            },
        ),
        migrations.CreateModel(
            name='DivisionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('branch', models.ManyToManyField(blank=True, to='base.Branch')),
                ('subordination', models.ManyToManyField(blank=True, related_name='_divisionsession_subordination_+', to='base.DivisionSession')),
            ],
            options={
                'verbose_name': 'Divisão ou Seção',
                'verbose_name_plural': 'Divisões e Seções',
            },
        ),
    ]
