# Generated by Django 3.1.2 on 2020-11-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('official_color', models.CharField(max_length=7)),
                ('image', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Arma/Quadro/Serviço',
                'verbose_name_plural': 'Armas/Quadros/Serviços',
            },
        ),
    ]
