# Generated by Django 3.1.2 on 2020-11-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201118_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='active',
            new_name='activate',
        ),
    ]
