# Generated by Django 3.1.2 on 2020-11-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201118_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertype',
            options={'ordering': ('activate',), 'verbose_name': 'Tipo de Identificação', 'verbose_name_plural': 'Tipos de Identificação'},
        ),
    ]
