# Generated by Django 3.1.3 on 2020-11-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_postgraduation_seniority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='image',
        ),
    ]
