# Generated by Django 3.1.3 on 2020-11-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_divisionsession_branch_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionsession',
            name='branch_main',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_main', to='base.branch'),
        ),
    ]
