# Generated by Django 3.1.3 on 2020-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_registertype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionsession',
            name='echelon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='divisionsession',
            name='subunit',
            field=models.BooleanField(default=False),
        ),
    ]
