# Generated by Django 3.1.6 on 2021-02-08 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201205_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('activate',), 'verbose_name': 'Ramal', 'verbose_name_plural': 'Ramais'},
        ),
        migrations.AlterModelOptions(
            name='divisionsession',
            options={'ordering': ('activate',), 'verbose_name': 'Divisão ou Seção', 'verbose_name_plural': 'Divisões e Seções'},
        ),
        migrations.AlterModelOptions(
            name='postgraduation',
            options={'ordering': ('activate',), 'verbose_name': 'Posto/Graduação', 'verbose_name_plural': 'Postos e Graduações'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ('activate',), 'verbose_name': 'Arma/Quadro/Serviço', 'verbose_name_plural': 'Armas/Quadros/Serviços'},
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='.', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgraduation',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='slug URL of the Post & Graduation.', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='abbreviation',
            field=models.CharField(help_text='.', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='telephone',
            field=models.CharField(help_text='.', max_length=4),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='name',
            field=models.CharField(help_text='Name of the Post & Graduation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='registertype',
            name='abbreviation',
            field=models.CharField(help_text='Abbreviation name of the RegisterType.', max_length=10),
        ),
        migrations.AlterField(
            model_name='registertype',
            name='activate',
            field=models.BooleanField(default=True, help_text='Activate and Deactivate RegisterType.'),
        ),
        migrations.AlterField(
            model_name='registertype',
            name='name',
            field=models.CharField(help_text='Name of the RegisterType.', max_length=100),
        ),
        migrations.AlterField(
            model_name='registertype',
            name='slug',
            field=models.SlugField(help_text='slug URL of the RegisterType.', unique=True),
        ),
    ]
